
name: Build Logseq Plugin

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'cmd-server/**'
      - 'script/**'
  workflow_dispatch:

env:
  PLUGIN_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Build
        id: build
        run: |
          pnpm i && pnpm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json icon.png ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT